<?php

namespace ShopBundle\Repository;

/**
 * ItemStatusRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ItemStatusRepository extends \Doctrine\ORM\EntityRepository
{
}
